Netcentric/accesscontroltool

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/AuthorizableCreatorServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java
The autosave feature is no longer supported by default.
https://issues.apache.org/jira/browse/OAK-1064
Change-Id: Ic559aadb02edbad7387bd48b9e7e28877bc06929
> Fix #19 User Management : OAK Differences to Jackrabbit 2.x.

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/AceService.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservicejmx/impl/AceServiceMBeanImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/AuthorizableConfigBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/AuthorizableCreatorServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configReader/ConfigReader.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configReader/YamlConfigReader.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configReader/YamlConfigurationMerger.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/CompleteAcDump.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/Dumpservice.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/impl/DumpserviceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/Constants.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/ConfigurationsValidator.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/YamlConfigurationsValidator.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configReader/YamlConfigReaderTest.java
allowing for a user_config section that has similar properties as the group_config section. Additionally, the property isSystemUser can be
set to true.
> #24 allow to create (system) users

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/ConfigFilesRetrieverImpl.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/ConfigFilesRetrieverImplTest.java
> #31 Extend runmode mechanism to allow "or" combination of runmodes 

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/HistoryEntry.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHook.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHookService.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHookServiceImpl.java
through the install hook.
Make install hook fail in case installation failed.
Fixes #25
> Expose messages from history in log during performing the install

- README.md
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/AuthorizableConfigBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/AuthorizableInstallationHistory.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/AuthorizableCreatorServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/Constants.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/impl/AuthorizableMemberGroupsValidator.java
allow anonymous in AuthorizableMemberGroupsValidator and handling of the setting in
AuthorizableCreatorServiceImpl.installAuthorizableConfigurationBean
Some additional cleanup
> #74 allow set set permissions for anonymous

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/AuthorizableCreatorServiceImpl.java
message in case if index still has some authorizable, but it doesn't
exist in the repository anymore
> #95 added a check for the NullPointerException with usefull error

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/AcHistoryService.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/AcInstallationHistoryPojo.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/impl/AcHistoryServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/impl/HistoryUtils.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHookServiceImpl.java
> #86 using correct config files for history node now when using install

- docs/AdvancedFeatures.md
> #108 declaration of conditional entry "IF" fixed to "- IF"

- README.md
- accesscontroltool-bundle/pom.xml
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/ConfigFilesRetriever.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/ConfigFilesRetrieverImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHook.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHookService.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHookServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/OsgiAwareInstallHook.java
> Migrate to new FileVault API

- accesscontroltool-bundle/pom.xml
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/healthcheck/LastRunSuccessHealthCheck.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/impl/AcHistoryServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installationhistory/impl/HistoryUtils.java
- docs/AdvancedFeatures.md
> #105 Adding Sling HC to warn if the last installation was not

- accesscontroltool-bundle/pom.xml
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/acls/AceBeanInstallerImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/AuthorizableCreatorServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/ExternalGroupCreatorServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AuthorizableConfigBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigReader.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroElEvaluator.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroProcessorImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/AcDumpElementYamlVisitor.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/impl/DumpserviceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/AcHelper.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/AccessControlUtils.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/impl/AuthorizableValidatorImpl.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroProcessorTest.java
- accesscontroltool-bundle/src/test/resources/test-variables-ldap.yaml
- accesscontroltool-bundle/src/test/resources/test-variables.yaml
- docs/AdvancedFeatures.md
- docs/Configuration.md
in order to allow to precreate LDAP groups. Also adding ability to use 
variables (#153)
> #140 Adding config attribute 'externalId'

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableutils/impl/AuthorizableCreatorServiceImpl.java
> #165 Fix for missing member assignment of new external groups on first

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/AceService.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservice/impl/AceServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservicejmx/AceServiceMBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceservicejmx/impl/AceServiceMBeanImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configuploadlistener/impl/UploadListenerServiceImpl.java
> #156 provide addtional api methods to supply alternative configuration

- docs/ApplyConfig.md
Due to #50 the CURL call has been updated in the docs/ApplyConfig.md
> CURL update in the docs/ApplyConfig.md

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/aceinstaller/BaseAceBeanInstaller.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/api/InstallationLog.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/ContentHelper.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/AcInstallationLog.java
> This closes #205# improved logging regarding missing parent paths in

- accesscontroltool-bundle/pom.xml
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configuploadlistener/impl/UploadListenerServiceImpl.java
- pom.xml
switch from JCR Observer to OSGi Event Handler
also defer triggering the ACTool (to wait for all YAML files to appear)
This fixes #217
> make UploadListener cluster-aware

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/healthcheck/LastRunSuccessHealthCheck.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/AcHistoryService.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/impl/AcHistoryServiceImpl.java
> #218 Warn in LastRunSuccessHealthCheck also if the HC history could not

- docs/Configuration.md
made clearer how this influence the final full group path and also explain how relative paths work
> Clarify path property

- pom.xml
> Update dependencies for AEM 6.1

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java
file for managed authorizables
This closes #268
> Explicitly clear profile properties which are not mentioned in the yaml

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AuthorizableConfigBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/AcDumpElementYamlVisitor.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/impl/DumpServiceImpl.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImplTest.java
> Evaluate return values of Group.addMember and Group.removeMember

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/ConfigFilesRetrieverImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMerger.java
> #261 allow empty config files

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/history/ProgressTrackerListenerInstallationLogger.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/impl/AcToolInstallHookServiceImpl.java
> Prevent NPE when InstallHook ProgressTrackerListner is missing

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java
> Made CryptoSupport optional for AuthorizableInstallerServiceImpl

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AcConfiguration.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AceBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AuthorizableConfigBean.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/VirtualGroupProcessor.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigReader.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMerger.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/AcDumpElementYamlVisitor.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/impl/DumpServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/impl/AuthorizableValidatorImpl.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/VirtualGroupProcessorTest.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMergerTest.java
- accesscontroltool-bundle/src/test/resources/test-virtualgroups-invalid-use-of-members.yaml
- accesscontroltool-bundle/src/test/resources/test-virtualgroups-multiple-levels.yaml
- accesscontroltool-bundle/src/test/resources/test-virtualgroups.yaml
- docs/Configuration.md
> #301 virtual groups

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AutoCreateTestUsersConfig.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/GlobalConfiguration.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/TestUserConfigsCreator.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMerger.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMergerTest.java
- docs/AdvancedFeatures.md
> #208 Allow automatic creation of test users

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/AcDumpElementYamlVisitor.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/dumpservice/impl/DumpServiceImpl.java
> #304 Added isSystemUser: true in dump

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/GlobalConfiguration.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMerger.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/UnmangedExternalMemberRelationshipChecker.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/validators/UnmangedExternalMemberRelationshipCheckerTest.java
- accesscontroltool-bundle/src/test/resources/invalid-unmanaged/test-invalid-unmanged-isMemberOf1.yaml
- accesscontroltool-bundle/src/test/resources/invalid-unmanaged/test-invalid-unmanged-isMemberOf2.yaml
- accesscontroltool-bundle/src/test/resources/invalid-unmanaged/test-invalid-unmanged-members1.yaml
- accesscontroltool-bundle/src/test/resources/invalid-unmanaged/test-invalid-unmanged-members2.yaml
- docs/AdvancedFeatures.md
> #244 Validation of unmanged aspects and documentation

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImplTest.java
> #308 fix initial pw if it is encrypted

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AuthorizableConfigBean.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/VirtualGroupProcessorTest.java
- accesscontroltool-bundle/src/test/resources/test-virtualgroups-inherit-from-multiple-vgroups.yaml
> #316 fix the problem that virtual groups fail if isMemberOf of using group becomes empty after flattening

- accesscontroltool-bundle/pom.xml
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java
- pom.xml
> restore compatibility with old configuration PID

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroElEvaluator.java
> Don't use reflection to instantiate the ExpressionFactoryImpl

- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigReader.java
- accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroProcessorImpl.java
- accesscontroltool-bundle/src/test/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroProcessorTest.java
- accesscontroltool-bundle/src/test/resources/test-loop-with-special-characters.yaml
> #330 Allow dot in literals list of for loop
